name: Deployment pipeline
on: 
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      # Run checkout action
      - uses: actions/checkout@v4
      # Setup Node.js to use package.json commands
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check coding style
        run: npm run eslint